module Hanzoai
  module Models
    module Organization
      type info_deprecated_params =
        { organizations: ::Array[String] } & Hanzoai::request_parameters

      class InfoDeprecatedParams < Hanzoai::BaseModel
        extend Hanzoai::RequestParameters::Converter
        include Hanzoai::RequestParameters

        attr_accessor organizations: ::Array[String]

        def initialize: (
          organizations: ::Array[String],
          ?request_options: Hanzoai::request_opts
        ) -> void

        def to_hash: -> Hanzoai::Models::Organization::info_deprecated_params
      end
    end
  end
end
