module Hanzoai
  module Models
    module Threads
      type run_create_params = {  } & Hanzoai::request_parameters

      class RunCreateParams < Hanzoai::BaseModel
        extend Hanzoai::RequestParameters::Converter
        include Hanzoai::RequestParameters

        def initialize: (?request_options: Hanzoai::request_opts) -> void

        def to_hash: -> Hanzoai::Models::Threads::run_create_params
      end
    end
  end
end
