module Hanzoai
  module Resources
    class Images
      class Generations
        def create: (?request_options: Hanzoai::request_opts) -> top

        def initialize: (client: Hanzoai::Client) -> void
      end
    end
  end
end
