module Hanzoai
  module Models
    module Batches
      type cancel_cancel_params =
        { provider: String? } & Hanzoai::request_parameters

      class CancelCancelParams < Hanzoai::BaseModel
        extend Hanzoai::RequestParameters::Converter
        include Hanzoai::RequestParameters

        attr_accessor provider: String?

        def initialize: (
          ?provider: String?,
          ?request_options: Hanzoai::request_opts
        ) -> void

        def to_hash: -> Hanzoai::Models::Batches::cancel_cancel_params
      end
    end
  end
end
