module HanzoAI
  module Models
    type active_list_callbacks_params = {  } & HanzoAI::request_parameters

    class ActiveListCallbacksParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::active_list_callbacks_params
    end
  end
end
