module HanzoAI
  module Models
    type anthropic_modify_params = {  } & HanzoAI::request_parameters

    class AnthropicModifyParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::anthropic_modify_params
    end
  end
end
