module HanzoAI
  module Models
    type batch_retrieve_params =
      { provider: String? } & HanzoAI::request_parameters

    class BatchRetrieveParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor provider: String?

      def initialize: (
        ?provider: String?,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::batch_retrieve_params
    end
  end
end
