module HanzoAI
  module Models
    type batch_list_with_provider_params =
      { after: String?, limit: Integer? } & HanzoAI::request_parameters

    class BatchListWithProviderParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor after: String?

      attr_accessor limit: Integer?

      def initialize: (
        ?after: String?,
        ?limit: Integer?,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::batch_list_with_provider_params
    end
  end
end
