module HanzoAI
  module Models
    type budget_update_params = {  } & HanzoAI::request_parameters

    class BudgetUpdateParams < HanzoAI::Models::BudgetNew
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::budget_update_params
    end
  end
end
