module HanzoAI
  module Models
    type cache_delete_params = {  } & HanzoAI::request_parameters

    class CacheDeleteParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::cache_delete_params
    end
  end
end
