module HanzoAI
  module Models
    type client_get_home_params = {  } & HanzoAI::request_parameters

    class ClientGetHomeParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::client_get_home_params
    end
  end
end
