module HanzoAI
  module Models
    type credential_create_params =
      {
        credential_info: top,
        credential_name: String,
        credential_values: top?,
        model_id: String?
      }
      & HanzoAI::request_parameters

    class CredentialCreateParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor credential_info: top

      attr_accessor credential_name: String

      attr_accessor credential_values: top?

      attr_accessor model_id: String?

      def initialize: (
        credential_info: top,
        credential_name: String,
        ?credential_values: top?,
        ?model_id: String?,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::credential_create_params
    end
  end
end
