module HanzoAI
  module Models
    type credential_delete_params = {  } & HanzoAI::request_parameters

    class CredentialDeleteParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::credential_delete_params
    end
  end
end
