module HanzoAI
  module Models
    type customer_list_params = {  } & HanzoAI::request_parameters

    class CustomerListParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::customer_list_params
    end
  end
end
