module HanzoAI
  module Models
    type customer_unblock_params = {  } & HanzoAI::request_parameters

    class CustomerUnblockParams < HanzoAI::Models::BlockUsers
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::customer_unblock_params
    end
  end
end
