module HanzoAI
  module Models
    type delete_create_allowed_ip_params = {  } & HanzoAI::request_parameters

    class DeleteCreateAllowedIPParams < HanzoAI::Models::IPAddress
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::delete_create_allowed_ip_params
    end
  end
end
