module HanzoAI
  module Models
    type file_list_params = { purpose: String? } & HanzoAI::request_parameters

    class FileListParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor purpose: String?

      def initialize: (
        ?purpose: String?,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::file_list_params
    end
  end
end
