module HanzoAI
  module Models
    type file_retrieve_params =
      { provider: String } & HanzoAI::request_parameters

    class FileRetrieveParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor provider: String

      def initialize: (
        provider: String,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::file_retrieve_params
    end
  end
end
