module HanzoAI
  module Models
    type file_create_params =
      { file: (IO | StringIO), purpose: String, custom_llm_provider: String }
      & HanzoAI::request_parameters

    class FileCreateParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor file: IO | StringIO

      attr_accessor purpose: String

      attr_reader custom_llm_provider: String?

      def custom_llm_provider=: (String) -> String

      def initialize: (
        file: IO | StringIO,
        purpose: String,
        ?custom_llm_provider: String,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::file_create_params
    end
  end
end
