module HanzoAI
  module Models
    type gemini_create_params = {  } & HanzoAI::request_parameters

    class GeminiCreateParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::gemini_create_params
    end
  end
end
