module HanzoAI
  module Models
    type guardrail_list_response =
      { guardrails: ::Array[HanzoAI::Models::GuardrailListResponse::Guardrail] }

    class GuardrailListResponse < HanzoAI::BaseModel
      attr_accessor guardrails: ::Array[HanzoAI::Models::GuardrailListResponse::Guardrail]

      def initialize: (
        guardrails: ::Array[HanzoAI::Models::GuardrailListResponse::Guardrail]
      ) -> void

      def to_hash: -> HanzoAI::Models::guardrail_list_response

      type guardrail =
        {
          guardrail_info: top?,
          guardrail_name: String,
          llm_params: HanzoAI::Models::GuardrailListResponse::Guardrail::LlmParams
        }

      class Guardrail < HanzoAI::BaseModel
        attr_accessor guardrail_info: top?

        attr_accessor guardrail_name: String

        attr_accessor llm_params: HanzoAI::Models::GuardrailListResponse::Guardrail::LlmParams

        def initialize: (
          guardrail_info: top?,
          guardrail_name: String,
          llm_params: HanzoAI::Models::GuardrailListResponse::Guardrail::LlmParams
        ) -> void

        def to_hash: -> HanzoAI::Models::GuardrailListResponse::guardrail

        type llm_params =
          {
            guardrail: String,
            mode: HanzoAI::Models::GuardrailListResponse::Guardrail::LlmParams::mode,
            default_on: bool
          }

        class LlmParams < HanzoAI::BaseModel
          attr_accessor guardrail: String

          attr_accessor mode: HanzoAI::Models::GuardrailListResponse::Guardrail::LlmParams::mode

          attr_reader default_on: bool?

          def default_on=: (bool) -> bool

          def initialize: (
            guardrail: String,
            mode: HanzoAI::Models::GuardrailListResponse::Guardrail::LlmParams::mode,
            ?default_on: bool
          ) -> void

          def to_hash: -> HanzoAI::Models::GuardrailListResponse::Guardrail::llm_params

          type mode = String | ::Array[String]

          module Mode
            extend HanzoAI::Union

            type string_array = ::Array[String]

            StringArray: string_array

            def self?.variants: -> [String, ::Array[String]]
          end
        end
      end
    end
  end
end
