module HanzoAI
  module Models
    type health_check_liveness_params = {  } & HanzoAI::request_parameters

    class HealthCheckLivenessParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::health_check_liveness_params
    end
  end
end
