module HanzoAI
  module Models
    type ip_address = { ip: String }

    class IPAddress < HanzoAI::BaseModel
      attr_accessor ip: String

      def initialize: (ip: String) -> void

      def to_hash: -> HanzoAI::Models::ip_address
    end
  end
end
