module HanzoAI
  module Models
    type key_unblock_params =
      { llm_changed_by: String } & HanzoAI::request_parameters

    class KeyUnblockParams < HanzoAI::Models::BlockKeyRequest
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def llm_changed_by: -> String?

      def llm_changed_by=: (String _) -> String

      def initialize: (
        ?llm_changed_by: String,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::key_unblock_params
    end
  end
end
