module HanzoAI
  module Models
    type member =
      {
        role: HanzoAI::Models::Member::role,
        user_email: String?,
        user_id: String?
      }

    class Member < HanzoAI::BaseModel
      attr_accessor role: HanzoAI::Models::Member::role

      attr_accessor user_email: String?

      attr_accessor user_id: String?

      def initialize: (
        role: HanzoAI::Models::Member::role,
        ?user_email: String?,
        ?user_id: String?
      ) -> void

      def to_hash: -> HanzoAI::Models::member

      type role = :admin | :user

      module Role
        extend HanzoAI::Enum

        ADMIN: :admin
        USER: :user

        def self?.values: -> ::Array[HanzoAI::Models::Member::role]
      end
    end
  end
end
