module HanzoAI
  module Models
    type openai_patch_params = {  } & HanzoAI::request_parameters

    class OpenAIPatchParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::openai_patch_params
    end
  end
end
