module HanzoAI
  module Models
    type organization_update_member_response =
      {
        created_at: Time,
        organization_id: String,
        updated_at: Time,
        user_id: String,
        budget_id: String?,
        llm_budget_table: HanzoAI::Models::OrganizationUpdateMemberResponse::LlmBudgetTable?,
        spend: Float,
        user: top,
        user_role: String?
      }

    class OrganizationUpdateMemberResponse < HanzoAI::BaseModel
      attr_accessor created_at: Time

      attr_accessor organization_id: String

      attr_accessor updated_at: Time

      attr_accessor user_id: String

      attr_accessor budget_id: String?

      attr_accessor llm_budget_table: HanzoAI::Models::OrganizationUpdateMemberResponse::LlmBudgetTable?

      attr_reader spend: Float?

      def spend=: (Float) -> Float

      attr_reader user: top?

      def user=: (top) -> top

      attr_accessor user_role: String?

      def initialize: (
        created_at: Time,
        organization_id: String,
        updated_at: Time,
        user_id: String,
        ?budget_id: String?,
        ?llm_budget_table: HanzoAI::Models::OrganizationUpdateMemberResponse::LlmBudgetTable?,
        ?spend: Float,
        ?user: top,
        ?user_role: String?
      ) -> void

      def to_hash: -> HanzoAI::Models::organization_update_member_response

      type llm_budget_table =
        {
          budget_duration: String?,
          max_budget: Float?,
          max_parallel_requests: Integer?,
          model_max_budget: top?,
          rpm_limit: Integer?,
          soft_budget: Float?,
          tpm_limit: Integer?
        }

      class LlmBudgetTable < HanzoAI::BaseModel
        attr_accessor budget_duration: String?

        attr_accessor max_budget: Float?

        attr_accessor max_parallel_requests: Integer?

        attr_accessor model_max_budget: top?

        attr_accessor rpm_limit: Integer?

        attr_accessor soft_budget: Float?

        attr_accessor tpm_limit: Integer?

        def initialize: (
          ?budget_duration: String?,
          ?max_budget: Float?,
          ?max_parallel_requests: Integer?,
          ?model_max_budget: top?,
          ?rpm_limit: Integer?,
          ?soft_budget: Float?,
          ?tpm_limit: Integer?
        ) -> void

        def to_hash: -> HanzoAI::Models::OrganizationUpdateMemberResponse::llm_budget_table
      end
    end
  end
end
