module HanzoAI
  module Models
    type provider_list_budgets_params = {  } & HanzoAI::request_parameters

    class ProviderListBudgetsParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::provider_list_budgets_params
    end
  end
end
