module HanzoAI
  module Models
    type team_disable_logging_params = {  } & HanzoAI::request_parameters

    class TeamDisableLoggingParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::team_disable_logging_params
    end
  end
end
