module HanzoAI
  module Models
    type team_list_available_params =
      { response_model: top } & HanzoAI::request_parameters

    class TeamListAvailableParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_reader response_model: top?

      def response_model=: (top) -> top

      def initialize: (
        ?response_model: top,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::team_list_available_params
    end
  end
end
