module HanzoAI
  module Models
    type team_list_params =
      { organization_id: String?, user_id: String? }
      & HanzoAI::request_parameters

    class TeamListParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor organization_id: String?

      attr_accessor user_id: String?

      def initialize: (
        ?organization_id: String?,
        ?user_id: String?,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::team_list_params
    end
  end
end
