module HanzoAI
  module Models
    type test_ping_params = {  } & HanzoAI::request_parameters

    class TestPingParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      def initialize: (?request_options: HanzoAI::request_opts) -> void

      def to_hash: -> HanzoAI::Models::test_ping_params
    end
  end
end
