module HanzoAI
  module Models
    type user_retrieve_info_params =
      { user_id: String? } & HanzoAI::request_parameters

    class UserRetrieveInfoParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor user_id: String?

      def initialize: (
        ?user_id: String?,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::user_retrieve_info_params
    end
  end
end
