module HanzoAI
  module Models
    type util_token_counter_params =
      { model: String, messages: ::Array[top]?, prompt: String? }
      & HanzoAI::request_parameters

    class UtilTokenCounterParams < HanzoAI::BaseModel
      extend HanzoAI::RequestParameters::Converter
      include HanzoAI::RequestParameters

      attr_accessor model: String

      attr_accessor messages: ::Array[top]?

      attr_accessor prompt: String?

      def initialize: (
        model: String,
        ?messages: ::Array[top]?,
        ?prompt: String?,
        ?request_options: HanzoAI::request_opts
      ) -> void

      def to_hash: -> HanzoAI::Models::util_token_counter_params
    end
  end
end
