module HanzoAI
  module Models
    type util_token_counter_response =
      {
        model_used: String,
        request_model: String,
        tokenizer_type: String,
        total_tokens: Integer
      }

    class UtilTokenCounterResponse < HanzoAI::BaseModel
      attr_accessor model_used: String

      attr_accessor request_model: String

      attr_accessor tokenizer_type: String

      attr_accessor total_tokens: Integer

      def initialize: (
        model_used: String,
        request_model: String,
        tokenizer_type: String,
        total_tokens: Integer
      ) -> void

      def to_hash: -> HanzoAI::Models::util_token_counter_response
    end
  end
end
