module HanzoAI
  module Resources
    class Add
      def add_allowed_ip: (
        ip: String,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
