module HanzoAI
  module Resources
    class Audio
      attr_reader speech: HanzoAI::Resources::Audio::Speech

      attr_reader transcriptions: HanzoAI::Resources::Audio::Transcriptions

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
