module HanzoAI
  module Resources
    class Cohere
      def create: (
        String endpoint,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def retrieve: (
        String endpoint,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def update: (
        String endpoint,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def delete: (
        String endpoint,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def modify: (
        String endpoint,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
