module HanzoAI
  module Resources
    class Credentials
      def create: (
        credential_info: top,
        credential_name: String,
        ?credential_values: top?,
        ?model_id: String?,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def list: (?request_options: HanzoAI::request_opts) -> top

      def delete: (
        String credential_name,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
