module HanzoAI
  module Resources
    class Engines
      attr_reader chat: HanzoAI::Resources::Engines::Chat

      def complete: (
        String model,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def embed: (String model, ?request_options: HanzoAI::request_opts) -> top

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
