module HanzoAI
  module Resources
    class Guardrails
      def list: (
        ?request_options: HanzoAI::request_opts
      ) -> HanzoAI::Models::GuardrailListResponse

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
