module HanzoAI
  module Resources
    class Model
      attr_reader info: HanzoAI::Resources::Model::Info

      attr_reader update: HanzoAI::Resources::Model::Update

      def create: (
        llm_params: HanzoAI::Models::ModelCreateParams::LlmParams,
        model_info: HanzoAI::Models::ModelInfo,
        model_name: String,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def delete: (id: String, ?request_options: HanzoAI::request_opts) -> top

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
