module HanzoAI
  module Resources
    class Provider
      def list_budgets: (
        ?request_options: HanzoAI::request_opts
      ) -> HanzoAI::Models::ProviderListBudgetsResponse

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
