module HanzoAI
  module Resources
    class Responses
      attr_reader input_items: HanzoAI::Resources::Responses::InputItems

      def create: (?request_options: HanzoAI::request_opts) -> top

      def retrieve: (
        String response_id,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def delete: (
        String response_id,
        ?request_options: HanzoAI::request_opts
      ) -> top

      def initialize: (client: HanzoAI::Client) -> void
    end
  end
end
