module HanzoAI
  module Models
    module OpenAI
      type deployment_complete_params = {  } & HanzoAI::request_parameters

      class DeploymentCompleteParams < HanzoAI::BaseModel
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        def initialize: (?request_options: HanzoAI::request_opts) -> void

        def to_hash: -> HanzoAI::Models::OpenAI::deployment_complete_params
      end
    end
  end
end
