configured_endpoints: 188
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hanzo-industries-inc%2FHanzo-AI-d52d95e1cfea66db609fe20a4ebf5612dbb3b8f6bd1d444f43953dedf8fe55c5.yml
openapi_spec_hash: cab16da993c22dfa62f6e845990ff29f
config_hash: ba350ab5c18ad5058636cd0062736ace
