module HanzoAI
  module Models
    module Config
      type pass_through_endpoint_create_params =
        {  } & HanzoAI::request_parameters

      class PassThroughEndpointCreateParams < HanzoAI::Models::Config::PassThroughGenericEndpoint
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        def initialize: (?request_options: HanzoAI::request_opts) -> void

        def to_hash: -> HanzoAI::Models::Config::pass_through_endpoint_create_params
      end
    end
  end
end
