module HanzoAI
  module Models
    module Config
      type pass_through_endpoint_response =
        {
          endpoints: ::Array[HanzoAI::Models::Config::PassThroughGenericEndpoint]
        }

      class PassThroughEndpointResponse < HanzoAI::BaseModel
        attr_accessor endpoints: ::Array[HanzoAI::Models::Config::PassThroughGenericEndpoint]

        def initialize: (
          endpoints: ::Array[HanzoAI::Models::Config::PassThroughGenericEndpoint]
        ) -> void

        def to_hash: -> HanzoAI::Models::Config::pass_through_endpoint_response
      end
    end
  end
end
