module HanzoAI
  module Models
    module Config
      type pass_through_endpoint_list_params =
        { endpoint_id: String? } & HanzoAI::request_parameters

      class PassThroughEndpointListParams < HanzoAI::BaseModel
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        attr_accessor endpoint_id: String?

        def initialize: (
          ?endpoint_id: String?,
          ?request_options: HanzoAI::request_opts
        ) -> void

        def to_hash: -> HanzoAI::Models::Config::pass_through_endpoint_list_params
      end
    end
  end
end
