module Hanzoai
  module Models
    module Global
      type spend_list_tags_params =
        { end_date: String?, start_date: String?, tags: String? }
        & Hanzoai::request_parameters

      class SpendListTagsParams < Hanzoai::BaseModel
        extend Hanzoai::RequestParameters::Converter
        include Hanzoai::RequestParameters

        attr_accessor end_date: String?

        attr_accessor start_date: String?

        attr_accessor tags: String?

        def initialize: (
          ?end_date: String?,
          ?start_date: String?,
          ?tags: String?,
          ?request_options: Hanzoai::request_opts
        ) -> void

        def to_hash: -> Hanzoai::Models::Global::spend_list_tags_params
      end
    end
  end
end
