module HanzoAI
  module Models
    module Chat
      type completion_create_params =
        { model: String? } & HanzoAI::request_parameters

      class CompletionCreateParams < HanzoAI::BaseModel
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        attr_accessor model: String?

        def initialize: (
          ?model: String?,
          ?request_options: HanzoAI::request_opts
        ) -> void

        def to_hash: -> HanzoAI::Models::Chat::completion_create_params
      end
    end
  end
end
