module Hanzoai
  module Models
    type active_list_callbacks_params = {  } & Hanzoai::request_parameters

    class ActiveListCallbacksParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::active_list_callbacks_params
    end
  end
end
