module Hanzoai
  module Models
    type add_add_allowed_ip_params = {  } & Hanzoai::request_parameters

    class AddAddAllowedIPParams < Hanzoai::Models::IPAddress
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::add_add_allowed_ip_params
    end
  end
end
