module Hanzoai
  module Models
    type azure_patch_params = {  } & Hanzoai::request_parameters

    class AzurePatchParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::azure_patch_params
    end
  end
end
