module Hanzoai
  module Models
    type batch_list_params =
      { after: String?, limit: Integer?, provider: String? }
      & Hanzoai::request_parameters

    class BatchListParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor after: String?

      attr_accessor limit: Integer?

      attr_accessor provider: String?

      def initialize: (
        ?after: String?,
        ?limit: Integer?,
        ?provider: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::batch_list_params
    end
  end
end
