module Hanzoai
  module Models
    type budget_info_params =
      { budgets: ::Array[String] } & Hanzoai::request_parameters

    class BudgetInfoParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor budgets: ::Array[String]

      def initialize: (
        budgets: ::Array[String],
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::budget_info_params
    end
  end
end
