module Hanzoai
  module Models
    type cache_ping_params = {  } & Hanzoai::request_parameters

    class CachePingParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::cache_ping_params
    end
  end
end
