module Hanzoai
  module Models
    type cache_flush_all_params = {  } & Hanzoai::request_parameters

    class CacheFlushAllParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::cache_flush_all_params
    end
  end
end
