module Hanzoai
  module Models
    type cohere_modify_params = {  } & Hanzoai::request_parameters

    class CohereModifyParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::cohere_modify_params
    end
  end
end
