module Hanzoai
  module Models
    type configurable_clientside_params_custom_auth = { api_base: String }

    class ConfigurableClientsideParamsCustomAuth < Hanzoai::BaseModel
      attr_accessor api_base: String

      def initialize: (api_base: String) -> void

      def to_hash: -> Hanzoai::Models::configurable_clientside_params_custom_auth
    end
  end
end
