module Hanzoai
  module Models
    type credential_item =
      { credential_info: top, credential_name: String, credential_values: top }

    class CredentialItem < Hanzoai::BaseModel
      attr_accessor credential_info: top

      attr_accessor credential_name: String

      attr_accessor credential_values: top

      def initialize: (
        credential_info: top,
        credential_name: String,
        credential_values: top
      ) -> void

      def to_hash: -> Hanzoai::Models::credential_item
    end
  end
end
