module Hanzoai
  module Models
    type customer_list_params = {  } & Hanzoai::request_parameters

    class CustomerListParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::customer_list_params
    end
  end
end
