module Hanzoai
  module Models
    type customer_block_params = {  } & Hanzoai::request_parameters

    class CustomerBlockParams < Hanzoai::Models::BlockUsers
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::customer_block_params
    end
  end
end
