module Hanzoai
  module Models
    type customer_list_response_item =
      {
        blocked: bool,
        user_id: String,
        alias_: String?,
        allowed_model_region: Hanzoai::Models::CustomerListResponseItem::allowed_model_region?,
        default_model: String?,
        llm_budget_table: Hanzoai::Models::CustomerListResponseItem::LlmBudgetTable?,
        spend: Float
      }

    class CustomerListResponseItem < Hanzoai::BaseModel
      attr_accessor blocked: bool

      attr_accessor user_id: String

      attr_accessor alias_: String?

      attr_accessor allowed_model_region: Hanzoai::Models::CustomerListResponseItem::allowed_model_region?

      attr_accessor default_model: String?

      attr_accessor llm_budget_table: Hanzoai::Models::CustomerListResponseItem::LlmBudgetTable?

      attr_reader spend: Float?

      def spend=: (Float) -> Float

      def initialize: (
        blocked: bool,
        user_id: String,
        ?alias_: String?,
        ?allowed_model_region: Hanzoai::Models::CustomerListResponseItem::allowed_model_region?,
        ?default_model: String?,
        ?llm_budget_table: Hanzoai::Models::CustomerListResponseItem::LlmBudgetTable?,
        ?spend: Float
      ) -> void

      def to_hash: -> Hanzoai::Models::customer_list_response_item

      type allowed_model_region = :eu | :us

      module AllowedModelRegion
        extend Hanzoai::Enum

        EU: :eu
        US: :us

        def self?.values: -> ::Array[Hanzoai::Models::CustomerListResponseItem::allowed_model_region]
      end

      type llm_budget_table =
        {
          budget_duration: String?,
          max_budget: Float?,
          max_parallel_requests: Integer?,
          model_max_budget: top?,
          rpm_limit: Integer?,
          soft_budget: Float?,
          tpm_limit: Integer?
        }

      class LlmBudgetTable < Hanzoai::BaseModel
        attr_accessor budget_duration: String?

        attr_accessor max_budget: Float?

        attr_accessor max_parallel_requests: Integer?

        attr_accessor model_max_budget: top?

        attr_accessor rpm_limit: Integer?

        attr_accessor soft_budget: Float?

        attr_accessor tpm_limit: Integer?

        def initialize: (
          ?budget_duration: String?,
          ?max_budget: Float?,
          ?max_parallel_requests: Integer?,
          ?model_max_budget: top?,
          ?rpm_limit: Integer?,
          ?soft_budget: Float?,
          ?tpm_limit: Integer?
        ) -> void

        def to_hash: -> Hanzoai::Models::CustomerListResponseItem::llm_budget_table
      end
    end

    type customer_list_response =
      ::Array[Hanzoai::Models::CustomerListResponseItem]

    CustomerListResponse: customer_list_response
  end
end
