module Hanzoai
  module Models
    type engine_embed_params = {  } & Hanzoai::request_parameters

    class EngineEmbedParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::engine_embed_params
    end
  end
end
