module Hanzoai
  module Models
    type file_delete_params = { provider: String } & Hanzoai::request_parameters

    class FileDeleteParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor provider: String

      def initialize: (
        provider: String,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::file_delete_params
    end
  end
end
