module Hanzoai
  module Models
    type gemini_patch_params = {  } & Hanzoai::request_parameters

    class GeminiPatchParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::gemini_patch_params
    end
  end
end
