module Hanzoai
  module Models
    type generate_key_response =
      {
        expires: Time?,
        key: String,
        token: String?,
        aliases: top?,
        allowed_cache_controls: ::Array[top]?,
        blocked: bool?,
        budget_duration: String?,
        budget_id: String?,
        config: top?,
        created_by: String?,
        duration: String?,
        enforced_params: ::Array[String]?,
        guardrails: ::Array[String]?,
        key_alias: String?,
        key_name: String?,
        llm_budget_table: top,
        max_budget: Float?,
        max_parallel_requests: Integer?,
        metadata: top?,
        model_max_budget: top?,
        model_rpm_limit: top?,
        model_tpm_limit: top?,
        models: ::Array[top]?,
        permissions: top?,
        rpm_limit: Integer?,
        spend: Float?,
        tags: ::Array[String]?,
        team_id: String?,
        token_id: String?,
        tpm_limit: Integer?,
        updated_by: String?,
        user_id: String?
      }

    class GenerateKeyResponse < Hanzoai::BaseModel
      attr_accessor expires: Time?

      attr_accessor key: String

      attr_accessor token: String?

      attr_accessor aliases: top?

      attr_accessor allowed_cache_controls: ::Array[top]?

      attr_accessor blocked: bool?

      attr_accessor budget_duration: String?

      attr_accessor budget_id: String?

      attr_accessor config: top?

      attr_accessor created_by: String?

      attr_accessor duration: String?

      attr_accessor enforced_params: ::Array[String]?

      attr_accessor guardrails: ::Array[String]?

      attr_accessor key_alias: String?

      attr_accessor key_name: String?

      attr_reader llm_budget_table: top?

      def llm_budget_table=: (top) -> top

      attr_accessor max_budget: Float?

      attr_accessor max_parallel_requests: Integer?

      attr_accessor metadata: top?

      attr_accessor model_max_budget: top?

      attr_accessor model_rpm_limit: top?

      attr_accessor model_tpm_limit: top?

      attr_accessor models: ::Array[top]?

      attr_accessor permissions: top?

      attr_accessor rpm_limit: Integer?

      attr_accessor spend: Float?

      attr_accessor tags: ::Array[String]?

      attr_accessor team_id: String?

      attr_accessor token_id: String?

      attr_accessor tpm_limit: Integer?

      attr_accessor updated_by: String?

      attr_accessor user_id: String?

      def initialize: (
        expires: Time?,
        key: String,
        ?token: String?,
        ?aliases: top?,
        ?allowed_cache_controls: ::Array[top]?,
        ?blocked: bool?,
        ?budget_duration: String?,
        ?budget_id: String?,
        ?config: top?,
        ?created_by: String?,
        ?duration: String?,
        ?enforced_params: ::Array[String]?,
        ?guardrails: ::Array[String]?,
        ?key_alias: String?,
        ?key_name: String?,
        ?llm_budget_table: top,
        ?max_budget: Float?,
        ?max_parallel_requests: Integer?,
        ?metadata: top?,
        ?model_max_budget: top?,
        ?model_rpm_limit: top?,
        ?model_tpm_limit: top?,
        ?models: ::Array[top]?,
        ?permissions: top?,
        ?rpm_limit: Integer?,
        ?spend: Float?,
        ?tags: ::Array[String]?,
        ?team_id: String?,
        ?token_id: String?,
        ?tpm_limit: Integer?,
        ?updated_by: String?,
        ?user_id: String?
      ) -> void

      def to_hash: -> Hanzoai::Models::generate_key_response
    end
  end
end
