module Hanzoai
  module Models
    type health_check_all_params =
      { model: String? } & Hanzoai::request_parameters

    class HealthCheckAllParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor model: String?

      def initialize: (
        ?model: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::health_check_all_params
    end
  end
end
