module Hanzoai
  module Models
    type health_check_liveness_params = {  } & Hanzoai::request_parameters

    class HealthCheckLivenessParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::health_check_liveness_params
    end
  end
end
