module Hanzoai
  module Models
    type key_delete_params =
      {
        key_aliases: ::Array[String]?,
        keys: ::Array[String]?,
        llm_changed_by: String
      }
      & Hanzoai::request_parameters

    class KeyDeleteParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor key_aliases: ::Array[String]?

      attr_accessor keys: ::Array[String]?

      attr_reader llm_changed_by: String?

      def llm_changed_by=: (String) -> String

      def initialize: (
        ?key_aliases: ::Array[String]?,
        ?keys: ::Array[String]?,
        ?llm_changed_by: String,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::key_delete_params
    end
  end
end
