module Hanzoai
  module Models
    type langfuse_patch_params = {  } & Hanzoai::request_parameters

    class LangfusePatchParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::langfuse_patch_params
    end
  end
end
