module Hanzoai
  module Models
    type model_delete_params = { id: String } & Hanzoai::request_parameters

    class ModelDeleteParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::model_delete_params
    end
  end
end
