module Hanzoai
  module Models
    type model_list_params =
      { return_wildcard_routes: bool?, team_id: String? }
      & Hanzoai::request_parameters

    class ModelListParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor return_wildcard_routes: bool?

      attr_accessor team_id: String?

      def initialize: (
        ?return_wildcard_routes: bool?,
        ?team_id: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::model_list_params
    end
  end
end
