module Hanzoai
  module Models
    type org_member =
      {
        role: Hanzoai::Models::OrgMember::role,
        user_email: String?,
        user_id: String?
      }

    class OrgMember < Hanzoai::BaseModel
      attr_accessor role: Hanzoai::Models::OrgMember::role

      attr_accessor user_email: String?

      attr_accessor user_id: String?

      def initialize: (
        role: Hanzoai::Models::OrgMember::role,
        ?user_email: String?,
        ?user_id: String?
      ) -> void

      def to_hash: -> Hanzoai::Models::org_member

      type role = :org_admin | :internal_user | :internal_user_viewer

      module Role
        extend Hanzoai::Enum

        ORG_ADMIN: :org_admin
        INTERNAL_USER: :internal_user
        INTERNAL_USER_VIEWER: :internal_user_viewer

        def self?.values: -> ::Array[Hanzoai::Models::OrgMember::role]
      end
    end
  end
end
