module Hanzoai
  module Models
    type organization_update_params =
      {
        budget_id: String?,
        metadata: top?,
        models: ::Array[String]?,
        organization_alias: String?,
        organization_id: String?,
        spend: Float?,
        updated_by: String?
      }
      & Hanzoai::request_parameters

    class OrganizationUpdateParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor budget_id: String?

      attr_accessor metadata: top?

      attr_accessor models: ::Array[String]?

      attr_accessor organization_alias: String?

      attr_accessor organization_id: String?

      attr_accessor spend: Float?

      attr_accessor updated_by: String?

      def initialize: (
        ?budget_id: String?,
        ?metadata: top?,
        ?models: ::Array[String]?,
        ?organization_alias: String?,
        ?organization_id: String?,
        ?spend: Float?,
        ?updated_by: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::organization_update_params
    end
  end
end
