module Hanzoai
  module Models
    type organization_delete_member_params =
      { organization_id: String, user_email: String?, user_id: String? }
      & Hanzoai::request_parameters

    class OrganizationDeleteMemberParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor organization_id: String

      attr_accessor user_email: String?

      attr_accessor user_id: String?

      def initialize: (
        organization_id: String,
        ?user_email: String?,
        ?user_id: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::organization_delete_member_params
    end
  end
end
