module Hanzoai
  module Models
    type organization_delete_params =
      { organization_ids: ::Array[String] } & Hanzoai::request_parameters

    class OrganizationDeleteParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor organization_ids: ::Array[String]

      def initialize: (
        organization_ids: ::Array[String],
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::organization_delete_params
    end
  end
end
