module Hanzoai
  module Models
    type spend_list_logs_params =
      {
        api_key: String?,
        end_date: String?,
        request_id: String?,
        start_date: String?,
        user_id: String?
      }
      & Hanzoai::request_parameters

    class SpendListLogsParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor api_key: String?

      attr_accessor end_date: String?

      attr_accessor request_id: String?

      attr_accessor start_date: String?

      attr_accessor user_id: String?

      def initialize: (
        ?api_key: String?,
        ?end_date: String?,
        ?request_id: String?,
        ?start_date: String?,
        ?user_id: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::spend_list_logs_params
    end
  end
end
