module Hanzoai
  module Models
    type team_retrieve_info_params =
      { team_id: String } & Hanzoai::request_parameters

    class TeamRetrieveInfoParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_reader team_id: String?

      def team_id=: (String) -> String

      def initialize: (
        ?team_id: String,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::team_retrieve_info_params
    end
  end
end
