module Hanzoai
  module Models
    type team_create_params =
      {
        admins: ::Array[top],
        blocked: bool,
        budget_duration: String?,
        guardrails: ::Array[String]?,
        max_budget: Float?,
        members: ::Array[top],
        members_with_roles: ::Array[Hanzoai::Models::Member],
        metadata: top?,
        model_aliases: top?,
        models: ::Array[top],
        organization_id: String?,
        rpm_limit: Integer?,
        tags: ::Array[top]?,
        team_alias: String?,
        team_id: String?,
        tpm_limit: Integer?,
        llm_changed_by: String
      }
      & Hanzoai::request_parameters

    class TeamCreateParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_reader admins: ::Array[top]?

      def admins=: (::Array[top]) -> ::Array[top]

      attr_reader blocked: bool?

      def blocked=: (bool) -> bool

      attr_accessor budget_duration: String?

      attr_accessor guardrails: ::Array[String]?

      attr_accessor max_budget: Float?

      attr_reader members: ::Array[top]?

      def members=: (::Array[top]) -> ::Array[top]

      attr_reader members_with_roles: ::Array[Hanzoai::Models::Member]?

      def members_with_roles=: (
        ::Array[Hanzoai::Models::Member]
      ) -> ::Array[Hanzoai::Models::Member]

      attr_accessor metadata: top?

      attr_accessor model_aliases: top?

      attr_reader models: ::Array[top]?

      def models=: (::Array[top]) -> ::Array[top]

      attr_accessor organization_id: String?

      attr_accessor rpm_limit: Integer?

      attr_accessor tags: ::Array[top]?

      attr_accessor team_alias: String?

      attr_accessor team_id: String?

      attr_accessor tpm_limit: Integer?

      attr_reader llm_changed_by: String?

      def llm_changed_by=: (String) -> String

      def initialize: (
        ?admins: ::Array[top],
        ?blocked: bool,
        ?budget_duration: String?,
        ?guardrails: ::Array[String]?,
        ?max_budget: Float?,
        ?members: ::Array[top],
        ?members_with_roles: ::Array[Hanzoai::Models::Member],
        ?metadata: top?,
        ?model_aliases: top?,
        ?models: ::Array[top],
        ?organization_id: String?,
        ?rpm_limit: Integer?,
        ?tags: ::Array[top]?,
        ?team_alias: String?,
        ?team_id: String?,
        ?tpm_limit: Integer?,
        ?llm_changed_by: String,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::team_create_params
    end
  end
end
