module Hanzoai
  module Models
    type team_remove_member_params =
      { team_id: String, user_email: String?, user_id: String? }
      & Hanzoai::request_parameters

    class TeamRemoveMemberParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor team_id: String

      attr_accessor user_email: String?

      attr_accessor user_id: String?

      def initialize: (
        team_id: String,
        ?user_email: String?,
        ?user_id: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::team_remove_member_params
    end
  end
end
