module Hanzoai
  module Models
    type team_block_params = {  } & Hanzoai::request_parameters

    class TeamBlockParams < Hanzoai::Models::BlockTeamRequest
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      def initialize: (?request_options: Hanzoai::request_opts) -> void

      def to_hash: -> Hanzoai::Models::team_block_params
    end
  end
end
