module Hanzoai
  module Models
    type team_delete_params =
      { team_ids: ::Array[String], llm_changed_by: String }
      & Hanzoai::request_parameters

    class TeamDeleteParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor team_ids: ::Array[String]

      attr_reader llm_changed_by: String?

      def llm_changed_by=: (String) -> String

      def initialize: (
        team_ids: ::Array[String],
        ?llm_changed_by: String,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::team_delete_params
    end
  end
end
