module Hanzoai
  module Models
    type user_retrieve_info_params =
      { user_id: String? } & Hanzoai::request_parameters

    class UserRetrieveInfoParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor user_id: String?

      def initialize: (
        ?user_id: String?,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::user_retrieve_info_params
    end
  end
end
