module Hanzoai
  module Models
    type user_delete_params =
      { user_ids: ::Array[String], llm_changed_by: String }
      & Hanzoai::request_parameters

    class UserDeleteParams < Hanzoai::BaseModel
      extend Hanzoai::RequestParameters::Converter
      include Hanzoai::RequestParameters

      attr_accessor user_ids: ::Array[String]

      attr_reader llm_changed_by: String?

      def llm_changed_by=: (String) -> String

      def initialize: (
        user_ids: ::Array[String],
        ?llm_changed_by: String,
        ?request_options: Hanzoai::request_opts
      ) -> void

      def to_hash: -> Hanzoai::Models::user_delete_params
    end
  end
end
