module HanzoAI
  module Models
    module Organization
      type info_deprecated_params =
        { organizations: ::Array[String] } & HanzoAI::request_parameters

      class InfoDeprecatedParams < HanzoAI::BaseModel
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        attr_accessor organizations: ::Array[String]

        def initialize: (
          organizations: ::Array[String],
          ?request_options: HanzoAI::request_opts
        ) -> void

        def to_hash: -> HanzoAI::Models::Organization::info_deprecated_params
      end
    end
  end
end
