module HanzoAI
  module Models
    module Organization
      type info_retrieve_params =
        { organization_id: String } & HanzoAI::request_parameters

      class InfoRetrieveParams < HanzoAI::BaseModel
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        attr_accessor organization_id: String

        def initialize: (
          organization_id: String,
          ?request_options: HanzoAI::request_opts
        ) -> void

        def to_hash: -> HanzoAI::Models::Organization::info_retrieve_params
      end
    end
  end
end
