module Hanzoai
  module Resources
    class FineTuning
      class Jobs
        attr_reader cancel: Hanzoai::Resources::FineTuning::Jobs::Cancel

        def create: (
          custom_llm_provider: Hanzoai::Models::FineTuning::JobCreateParams::custom_llm_provider,
          model: String,
          training_file: String,
          ?hyperparameters: Hanzoai::Models::FineTuning::JobCreateParams::Hyperparameters?,
          ?integrations: ::Array[String]?,
          ?seed: Integer?,
          ?suffix: String?,
          ?validation_file: String?,
          ?request_options: Hanzoai::request_opts
        ) -> top

        def retrieve: (
          String fine_tuning_job_id,
          custom_llm_provider: Hanzoai::Models::FineTuning::JobRetrieveParams::custom_llm_provider,
          ?request_options: Hanzoai::request_opts
        ) -> top

        def list: (
          custom_llm_provider: Hanzoai::Models::FineTuning::JobListParams::custom_llm_provider,
          ?after: String?,
          ?limit: Integer?,
          ?request_options: Hanzoai::request_opts
        ) -> top

        def initialize: (client: Hanzoai::Client) -> void
      end
    end
  end
end
