module Hanzoai
  module Resources
    class Assistants
      def create: (?request_options: Hanzoai::request_opts) -> top

      def list: (?request_options: Hanzoai::request_opts) -> top

      def delete: (
        String assistant_id,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def initialize: (client: Hanzoai::Client) -> void
    end
  end
end
