module Hanzoai
  module Resources
    class Batches
      attr_reader cancel: Hanzoai::Resources::Batches::Cancel

      def create: (
        ?provider: String?,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def retrieve: (
        String batch_id,
        ?provider: String?,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def list: (
        ?after: String?,
        ?limit: Integer?,
        ?provider: String?,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def cancel_with_provider: (
        String batch_id,
        provider: String,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def create_with_provider: (
        String provider,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def list_with_provider: (
        String provider,
        ?after: String?,
        ?limit: Integer?,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def retrieve_with_provider: (
        String batch_id,
        provider: String,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def initialize: (client: Hanzoai::Client) -> void
    end
  end
end
