module Hanzoai
  module Resources
    class ModelGroup
      def retrieve_info: (
        ?model_group: String?,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def initialize: (client: Hanzoai::Client) -> void
    end
  end
end
