module Hanzoai
  module Resources
    class Models
      def list: (
        ?return_wildcard_routes: bool?,
        ?team_id: String?,
        ?request_options: Hanzoai::request_opts
      ) -> top

      def initialize: (client: Hanzoai::Client) -> void
    end
  end
end
