module Hanzoai
  module Resources
    class Rerank
      def create: (?request_options: Hanzoai::request_opts) -> top

      def create_v1: (?request_options: Hanzoai::request_opts) -> top

      def create_v2: (?request_options: Hanzoai::request_opts) -> top

      def initialize: (client: Hanzoai::Client) -> void
    end
  end
end
