module Hanzoai
  module Resources
    class Config
      class PassThroughEndpoint
        def create: (
          headers: top,
          path: String,
          target: String,
          ?request_options: Hanzoai::request_opts
        ) -> top

        def update: (
          String endpoint_id,
          ?request_options: Hanzoai::request_opts
        ) -> top

        def list: (
          ?endpoint_id: String?,
          ?request_options: Hanzoai::request_opts
        ) -> Hanzoai::Models::Config::PassThroughEndpointResponse

        def delete: (
          endpoint_id: String,
          ?request_options: Hanzoai::request_opts
        ) -> Hanzoai::Models::Config::PassThroughEndpointResponse

        def initialize: (client: Hanzoai::Client) -> void
      end
    end
  end
end
