module HanzoAI
  module Resources
    class FineTuning
      class Jobs
        class Cancel
          def create: (
            String fine_tuning_job_id,
            ?request_options: HanzoAI::request_opts
          ) -> top

          def initialize: (client: HanzoAI::Client) -> void
        end
      end
    end
  end
end
