module HanzoAI
  module Models
    module OpenAI
      module Deployments
        type chat_complete_params = {  } & HanzoAI::request_parameters

        class ChatCompleteParams < HanzoAI::BaseModel
          extend HanzoAI::RequestParameters::Converter
          include HanzoAI::RequestParameters

          def initialize: (?request_options: HanzoAI::request_opts) -> void

          def to_hash: -> HanzoAI::Models::OpenAI::Deployments::chat_complete_params
        end
      end
    end
  end
end
