module Hanzoai
  module Models
    module Team
      type callback_retrieve_params = {  } & Hanzoai::request_parameters

      class CallbackRetrieveParams < Hanzoai::BaseModel
        extend Hanzoai::RequestParameters::Converter
        include Hanzoai::RequestParameters

        def initialize: (?request_options: Hanzoai::request_opts) -> void

        def to_hash: -> Hanzoai::Models::Team::callback_retrieve_params
      end
    end
  end
end
