module HanzoAI
  module Resources
    class OpenAI
      class Deployments
        attr_reader chat: HanzoAI::Resources::OpenAI::Deployments::Chat

        def complete: (
          String model,
          ?request_options: HanzoAI::request_opts
        ) -> top

        def embed: (
          String model,
          ?request_options: HanzoAI::request_opts
        ) -> top

        def initialize: (client: HanzoAI::Client) -> void
      end
    end
  end
end
