module HanzoAI
  module Models
    module Responses
      type input_item_list_params = {  } & HanzoAI::request_parameters

      class InputItemListParams < HanzoAI::BaseModel
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        def initialize: (?request_options: HanzoAI::request_opts) -> void

        def to_hash: -> HanzoAI::Models::Responses::input_item_list_params
      end
    end
  end
end
