module Hanzoai
  module Resources
    class Chat
      class Completions
        def create: (
          ?model: String?,
          ?request_options: Hanzoai::request_opts
        ) -> top

        def initialize: (client: Hanzoai::Client) -> void
      end
    end
  end
end
