module Hanzoai
  module Resources
    class OpenAI
      class Deployments
        class Chat
          def complete: (
            String model,
            ?request_options: Hanzoai::request_opts
          ) -> top

          def initialize: (client: Hanzoai::Client) -> void
        end
      end
    end
  end
end
