module HanzoAI
  module Resources
    class Team
      class Callback
        def retrieve: (
          String team_id,
          ?request_options: HanzoAI::request_opts
        ) -> top

        def add: (
          String team_id,
          callback_name: String,
          callback_vars: ::Hash[Symbol, String],
          ?callback_type: HanzoAI::Models::Team::CallbackAddParams::callback_type?,
          ?llm_changed_by: String,
          ?request_options: HanzoAI::request_opts
        ) -> top

        def initialize: (client: HanzoAI::Client) -> void
      end
    end
  end
end
