module Hanzoai
  module Models
    module Model
      type update_full_params = {  } & Hanzoai::request_parameters

      class UpdateFullParams < Hanzoai::Models::Model::UpdateDeployment
        extend Hanzoai::RequestParameters::Converter
        include Hanzoai::RequestParameters

        def initialize: (?request_options: Hanzoai::request_opts) -> void

        def to_hash: -> Hanzoai::Models::Model::update_full_params
      end
    end
  end
end
