module Hanzoai
  module Models
    module Model
      type update_partial_params = {  } & Hanzoai::request_parameters

      class UpdatePartialParams < Hanzoai::Models::Model::UpdateDeployment
        extend Hanzoai::RequestParameters::Converter
        include Hanzoai::RequestParameters

        def initialize: (?request_options: Hanzoai::request_opts) -> void

        def to_hash: -> Hanzoai::Models::Model::update_partial_params
      end
    end
  end
end
