module Hanzoai
  module Resources
    class Files
      class Content
        def retrieve: (
          String file_id,
          provider: String,
          ?request_options: Hanzoai::request_opts
        ) -> top

        def initialize: (client: Hanzoai::Client) -> void
      end
    end
  end
end
