module HanzoAI
  module Models
    module Global
      type spend_retrieve_report_params =
        {
          api_key: String?,
          customer_id: String?,
          end_date: String?,
          group_by: HanzoAI::Models::Global::SpendRetrieveReportParams::group_by?,
          internal_user_id: String?,
          start_date: String?,
          team_id: String?
        }
        & HanzoAI::request_parameters

      class SpendRetrieveReportParams < HanzoAI::BaseModel
        extend HanzoAI::RequestParameters::Converter
        include HanzoAI::RequestParameters

        attr_accessor api_key: String?

        attr_accessor customer_id: String?

        attr_accessor end_date: String?

        attr_accessor group_by: HanzoAI::Models::Global::SpendRetrieveReportParams::group_by?

        attr_accessor internal_user_id: String?

        attr_accessor start_date: String?

        attr_accessor team_id: String?

        def initialize: (
          ?api_key: String?,
          ?customer_id: String?,
          ?end_date: String?,
          ?group_by: HanzoAI::Models::Global::SpendRetrieveReportParams::group_by?,
          ?internal_user_id: String?,
          ?start_date: String?,
          ?team_id: String?,
          ?request_options: HanzoAI::request_opts
        ) -> void

        def to_hash: -> HanzoAI::Models::Global::spend_retrieve_report_params

        type group_by = :team | :customer | :api_key

        module GroupBy
          extend HanzoAI::Enum

          TEAM: :team
          CUSTOMER: :customer
          API_KEY: :api_key

          def self?.values: -> ::Array[HanzoAI::Models::Global::SpendRetrieveReportParams::group_by]
        end
      end
    end
  end
end
