module HanzoAI
  module Resources
    class Model
      class Update
        def full: (
          ?llm_params: HanzoAI::Models::Model::UpdateDeployment::LlmParams?,
          ?model_info: HanzoAI::Models::ModelInfo?,
          ?model_name: String?,
          ?request_options: HanzoAI::request_opts
        ) -> top

        def partial: (
          String model_id,
          ?llm_params: HanzoAI::Models::Model::UpdateDeployment::LlmParams?,
          ?model_info: HanzoAI::Models::ModelInfo?,
          ?model_name: String?,
          ?request_options: HanzoAI::request_opts
        ) -> top

        def initialize: (client: HanzoAI::Client) -> void
      end
    end
  end
end
