module HanzoAI
  module Resources
    class Global
      class Spend
        def list_tags: (
          ?end_date: String?,
          ?start_date: String?,
          ?tags: String?,
          ?request_options: HanzoAI::request_opts
        ) -> HanzoAI::Models::Global::spend_list_tags_response

        def reset: (?request_options: HanzoAI::request_opts) -> top

        def retrieve_report: (
          ?api_key: String?,
          ?customer_id: String?,
          ?end_date: String?,
          ?group_by: HanzoAI::Models::Global::SpendRetrieveReportParams::group_by?,
          ?internal_user_id: String?,
          ?start_date: String?,
          ?team_id: String?,
          ?request_options: HanzoAI::request_opts
        ) -> HanzoAI::Models::Global::spend_retrieve_report_response

        def initialize: (client: HanzoAI::Client) -> void
      end
    end
  end
end
